name: food_pick_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  daum_postcode_search: ^0.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.8.0
  flutter_naver_map: ^1.2.3+1
  geolocator: ^12.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  supabase_flutter: ^2.5.8

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - .env
  uses-material-design: true
